{% set version = '1.1.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-robslopes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/robslopes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/robslopes/robslopes_{{ version }}.tar.gz
  sha256: 65ed8a10b9c9ec16876240d6623661dc134c317dc69ccf4d0fc72d3fc0bd0d42

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.5
    - r-rcpparmadillo
  run:
    - r-base
    - r-rcpp >=1.0.5
    - r-rcpparmadillo

test:
  commands:
    - $R -e "library('robslopes')"           # [not win]
    - "\"%R%\" -e \"library('robslopes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=robslopes
  license: GPL-2.0-only
  summary: Fast algorithms for the Theil-Sen estimator, Siegel's repeated median slope estimator,
    and Passing-Bablok regression. The implementation is based on algorithms by Dillencourt
    et. al (1992) <doi:10.1142/S0218195992000020> and Matousek et. al (1998)  <doi:10.1007/PL00009190>.
    The implementations are detailed in Raymaekers (2023) <doi:10.32614/RJ-2023-012>
    and Raymaekers J., Dufey F. (2022) <arXiv:2202.08060>. All algorithms run in quasilinear
    time.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
